### PR TITLE
Fix `_get_descendant_accumulate_grads`

### LINKED ISSUE #216: `_get_descendant_accumulate_grads` stuck in infinite loop
The current implementation:

```python
def _get_descendant_accumulate_grads(roots: set[Node], excluded_nodes: set[Node]) -> set[Node]:
    """
    Gets the AccumulateGrad descendants of the specified nodes.

    :param roots: Root nodes from which the graph traversal should start.
    :param excluded_nodes: Nodes excluded from the graph traversal.
    """

    result = set()
    nodes_to_traverse = [node for node in roots if node not in excluded_nodes]

    # This implementation more or less follows what is advised
    # [here](https://discuss.pytorch.org/t/how-to-access-the-computational-graph/112887), but it is
    # not necessarily robust to future changes, and it's not guaranteed to work.
    # See [this](https://discuss.pytorch.org/t/autograd-graph-traversal/213658) for another question
    # about how to implement this.
    while nodes_to_traverse:
        current_node = nodes_to_traverse.pop()

        if current_node.__class__.__name__ == "AccumulateGrad":
            result.add(current_node)

        nodes_to_traverse += [
            child[0]
            for child in current_node.next_functions
            if child[0] is not None and child[0] not in excluded_nodes
        ]

    return result
```
    
Was stuck in an infinite loop when I ran torchjd.backward(), as nothing is ever added to excluded_nodes.
    
I re-wrote as:
    
```python
def _get_descendant_accumulate_grads(roots: set[Node], excluded_nodes: set[Node]) -> set[Node]:
    """
    Gets the AccumulateGrad descendants of the specified nodes.

    :param roots: Root nodes from which the graph traversal should start.
    :param excluded_nodes: Nodes excluded from the graph traversal.
    """

    result = set()
    q: deque[Node] = deque()
    
    # Initialize the queue with root nodes that are not in excluded_nodes
    for node in roots:
        if node is not None and node not in excluded_nodes:
            excluded_nodes.add(node)
            q.append(node)

    while q:
        current_node = q.popleft()
        
        # Check for AccumulateGrad nodes
        if current_node not in result and current_node.__class__.__name__ == "AccumulateGrad":
            result.add(current_node)

        # Add child nodes to the queue for further traversal
        for fn, _ in current_node.next_functions:
            if fn is not None and fn not in excluded_nodes:
                excluded_nodes.add(fn)
                q.append(fn)

    return result
```

I'm not a CS expert (testing this in a study I'm working on), so it may not be the right approach, but I'm now able to train with this revision.

### PR DESCRIPTION
**Pull request by ValerianRey**
- Fixes #216

### CODE REVIEW

**Comment by ValerianRey** [comment]
@austen260 could you tell me if this other implementation also works on your particular case? It's very similar to what you suggested, so I think it should.

**Review by PierreQuinton — APPROVED** [review]
We would need a test to reproduce the bug of course but otherwise LGTM.

**Comment by ValerianRey** [comment]
> We would need a test to reproduce the bug of course but otherwise LGTM.

Yes, I would also like to make sure that we can reproduce or understand the infinite loop bug before writing this changelog message

**Comment by PierreQuinton** [comment]
The thing is that we are pretty sure that this is better, so maybe we can merge without test and changelog and work on an additional PR with less priority for the test and the changelog, this is a bit irregular and is a bit dirty in terms of commits log.

**Comment by PierreQuinton** [comment]
Alternatively, we could code it like that:
```python

```

**Comment by PierreQuinton** [comment]
We could do something like this instead:
```python
def _get_descendant_accumulate_grads(roots: set[Node], excluded_nodes: set[Node]) -> set[Node]:

    excluded_nodes = set(excluded_nodes)  # Re-instantiate set to avoid modifying input
    nodes_to_traverse = deque([node for node in roots if node is not None])
    result = set()

    while nodes_to_traverse:
        current_node = nodes_to_traverse.popleft()  # Breadth-first
        excluded_nodes.add(current_node)

        if current_node.__class__.__name__ == "AccumulateGrad":
            result.add(current_node)

        for node, _ in current_node.next_functions:
            if node is not None and node not in excluded_nodes:
                nodes_to_traverse.append(node)  # Append to the right

    return result
```

This avoids duplicating the check `node not in excluded_nodes`, so this makes it more natural (and I think equivalent).

**Review by PierreQuinton — APPROVED** [review]

**Pull request merged**
