### PR TITLE
Make relative imports

### PR DESCRIPTION
**Pull request by ValerianRey**
Fixes https://github.com/TorchJD/torchjd/issues/75
* Change within-package imports from absolute to relative
* Minor import improvements

### CODE REVIEW

**Comment by ValerianRey** [comment]
A drawback is that in PyCharm, <kbd>Ctrl</kbd>+<kbd>Enter</kbd> imports automatically with absolute path. We will have to manually make these imports instead, to keep using the relative style, whenever the import is from within the same package.

Also, for the `strategy` package, using relative imports leads to double dot:
```python
from ..tensor_dict import EmptyTensorDict, GradientVectors
```
This is because `strategy` depends on its parent package (`_transform`), which is weird and which will be fixed by #74 anyway.

**Comment by PierreQuinton** [comment]
> A drawback is that in PyCharm, Ctrl+Enter imports automatically with absolute path. We will have to manually make these imports instead, to keep using the relative style, whenever the import is from within the same package.
> 
> Also, for the `strategy` package, using relative imports leads to double dot:
> 
> ```python
> from ..tensor_dict import EmptyTensorDict, GradientVectors
> ```
> 
> This is because `strategy` depends on its parent package (`_transform`), which is weird and which will be fixed by #74 anyway.

That is fine I think, maybe we can configure PyCharm a bit differently. The second is fine too, we will remove strategy anyways.

**Comment by PierreQuinton** [comment]
I took a look and LGTM but I don't really know how to make sure it is fine. I'm trusting you did it exhaustively.

**Comment by ValerianRey** [comment]
> I took a look and LGTM but I don't really know how to make sure it is fine. I'm trusting you did it exhaustively.

I double-checked every file, and I missed one (in `tests/plots`). I fixed this.

**Pull request merged**
